### ISSUE TITLE
Vercel-prisma-supabase error: "prepared statement \"..\" already exists"

### ISSUE THREAD

**Issue by refringerator** [refringerator/itr_project_next#2]
```
PrismaClientUnknownRequestError: 
Invalid `prisma.item.findMany()` invocation:


Error occurred during query execution:
ConnectorError(ConnectorError { user_facing_error: None, kind: QueryError(PostgresError { code: "42P05", message: "prepared statement \"s2\" already exists", severity: "ERROR", detail: None, column: None, hint: None }), transient: false })
    at In.handleRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:7044)
    at In.handleAndLogRequestError (/var/task/node_modules/@prisma/client/runtime/library.js:122:6188)
    at In.request (/var/task/node_modules/@prisma/client/runtime/library.js:122:5896)
    at async l (/var/task/node_modules/@prisma/client/runtime/library.js:127:11167)
    at async f (/var/task/.next/server/app/items/page.js:1:6422)
    at async c (/var/task/.next/server/app/items/page.js:1:9218) {
  clientVersion: '5.13.0',
  digest: '686236828'
}
```

**Comment by refringerator** [comment]
step 1
add `&pgbouncer=true&connection_limit=1` to envs
as in https://supabase.com/partners/integrations/prisma
